### ISSUE TITLE
Batch 0.5

### ISSUE THREAD

**Issue by UrickMacario** [macario-publico/publico#1]
Hola Dan,

Aprovecharé el uso de esta herramienta para ir recopilando observaciones, cambios, etc. Y no tener que estar en la búsqueda histórica de mails, whatsapp, etc. Y podamos tener una conversación más fluida y ordenada. Estoy a favor de ocupar la tecnología. 

Te comparto un pequeño arbolweb que arme rápido del desarrollo que llevamos:
[x]Index
[x]Espacios de trabajo
    -[x]Muzquiz
    -[x]Puebla
    -[x]moliere
    -[x]seneca
    -[ ]hamburgo // De esta sección pongámosle la misma estructura que muzquiz (el contenido) para tener la estructura completa, ya que, cuando salga online, posiblemente sólo tenga un par de secciones de la estructura (foto y mapa + footer)Esto depende del cliente. **Te lo haré saber ASAP.**
    -[ ]lomas  // De esta sección pongámosle la misma estructura que muzquiz (el contenido) para tener la estructura completa, ya que, cuando salga online, posiblemente sólo tenga un par de secciones de la estructura (foto y mapa + footer)Esto depende del cliente. **Te lo haré saber ASAP**.
[x]comedores
[ ]estudio fotográfico la url para esta sección será: …/publico-estudio-fotografico-cdmx/
[x]about us
[ ]press
[ ]membresía
[ ]eventos
[ ]contacto
[ ]blog
[x]colaboradores
[ ]terminos y condiciones / preguntas frecuentes / políticas de privacidad
[x]bolsa de trabajo 

Revisando los archivos, encontré un par con nombres mal implementados.
· el archivo about.html es la sección Bolsa de trabajo (trabajo.html)
· el archivo trabajo.html es About Us (about.html)

Igual y me puedes estar comentando o informando, vale? 
Saludos.
U.

**Comment by UrickMacario** [comment]
Revisando el index, te comento los siguientes detalles:

· Redes sociales // Se puede poner un over al icono de la red social en blanco?


· Al icono que parece un mouse // hacerle más gruesa su linea. (subirlo a 3px)
<img width="264" alt="screen shot 2018-08-21 at 15 49 22" src="https://user-images.githubusercontent.com/26375886/44429181-333cd880-a55c-11e8-9150-7202016b61e5.png">


· Al icono de share, ponerle el fondo en este color #cb8070. Y darle más separación entre las redes sociales.


· En el apartado - "proximamente por abrir" // el tamaño de la tipografía de las direcciones (colonia juarez y lomás de chapultepec), colocarle los siguientes valores (son los mismos que ocupas en las cards):
color: #747373; font-size: .9rem; font-weight: 400;


· Entre las secciones de Nuestros servicios y los testimoniales podemos hacerla más corta, para no hacer el sitio muy "largo".
<img width="552" alt="screen shot 2018-08-21 at 16 26 51" src="https://user-images.githubusercontent.com/26375886/44430097-5026db00-a55f-11e8-817d-bc1b4ba60cb3.png">


· En el card de Nuestros colaboradores, PúblicoComedor / itacate y Nuestro blog, ponerle a la tipografía los mismos valores (son muy diferentes):
color: #747373; font-size: .9rem; font-weight: 400;


· A los botones de las cards mencionadas con anterioridad, bajarles el borde a 1px al igual que los dots de las galerías. 


· Los botones de las secciones de nuestros colaboradores, publico comedor /itacate, evento en publico y nuestro blog. No llevan sombra. Y el over que sea el color inverso del botón (negro).


· Sección de nuestro evento, el texto va justificado, no alineado a la izq.


· Falta colocar la textura de fondo de acuerdo al diseño.


· Las direcciones alinearlas a la izquierda.
<img width="266" alt="screen shot 2018-08-21 at 15 49 54" src="https://user-images.githubusercontent.com/26375886/44430389-1d311700-a560-11e8-8954-f7dedcd0ead2.png">


· El over del menú es azul, que sea de color #cb8070


**En responsive:**
· el icono de redes sociales ya no va ya que tenemos las redes hasta abajo en la pleca blanca.


· Colocar en columna "proximamente por abrir"
<img width="393" alt="screen shot 2018-08-21 at 16 40 09" src="https://user-images.githubusercontent.com/26375886/44430843-9aa95700-a561-11e8-883a-1b89efb4d8a6.png">


· Me imagino que con los cambios mencionados (para desktop) anteriormente de los tamaños tipográficos, estos tmb van a cambiar, no?
<img width="335" alt="screen shot 2018-08-21 at 16 41 35" src="https://user-images.githubusercontent.com/26375886/44430895-c298ba80-a561-11e8-804e-bb941ac7157a.png">

<img width="345" alt="screen shot 2018-08-21 at 16 41 27" src="https://user-images.githubusercontent.com/26375886/44430899-c593ab00-a561-11e8-8599-1d4dba27a224.png">


· En este apartado, podemos hacer qué solo aparezcan 4 en lugar de las 8?
<img width="347" alt="screen shot 2018-08-21 at 16 48 13" src="https://user-images.githubusercontent.com/26375886/44431003-1efbda00-a562-11e8-9206-b155bd257faf.png">


· Los logotipos, hacerlos más grandes en responsive.
<img width="329" alt="screen shot 2018-08-21 at 16 45 45" src="https://user-images.githubusercontent.com/26375886/44430984-0986b000-a562-11e8-9f9d-d5fcf35602be.png">

Estos sería mis tentativos últimos comentarios. Cualquier duda por fa, avísame. 
Quedo al pendiente.
Saludos.

**Comment by UrickMacario** [comment]
Hola DAN

· El tamaño de la tipo (con el mismo interlineado e interletrado, si es que tiene) implementada en los cards de las sucursales, tmb se debe de implementar en las siguientes secciones:

![tamano](https://user-images.githubusercontent.com/26375886/44474865-3df97b00-a5f9-11e8-85b4-8aab30bfd201.jpg)


· Los espacios entre título y los carruseles, disminuirlos, trate de buscar en el inspector la medida para dártela pero no la encontré.  En el ejemplo siguiente el rojo viene siendo la medida actual (digamos que es el 100%) y en verde el que se desea. (el 70% por darle el equivalente)

<img width="1280" alt="screen shot 2018-08-22 at 10 40 34" src="https://user-images.githubusercontent.com/26375886/44475014-9c265e00-a5f9-11e8-8164-2783232f4eac.png">

<img width="1280" alt="screen shot 2018-08-22 at 10 40 37" src="https://user-images.githubusercontent.com/26375886/44475099-ced05680-a5f9-11e8-8c6d-7349d3476d85.png">

<img width="1280" alt="screen shot 2018-08-22 at 10 40 57" src="https://user-images.githubusercontent.com/26375886/44475105-d263dd80-a5f9-11e8-8964-9900d4f2cd0d.png">

· El tamaño de los logotipos esta perfecto.
· Falta colocar la textura de fondo de acuerdo al diseño.


· De este card, mi error, no es justificado es centrado el texto.
<img width="178" alt="screen shot 2018-08-22 at 10 56 45" src="https://user-images.githubusercontent.com/26375886/44475264-2a024900-a5fa-11e8-98b0-175b8c15571a.png">
![44440557-32bd3580-a58e-11e8-89a2-7261dc8aa282](https://user-images.githubusercontent.com/26375886/44475258-25d62b80-a5fa-11e8-8ca7-73d29e532591.png)

**Comment by Danlouis9701** [comment]
El tamaño de la tipo   (cerrado)
 Los espacios entre título y los carruseles (cerrado)
La textura quedo muy pequeña creo, no se quieras cambiarla
![captura de pantalla 2018-08-22 a la s 15 14 32](https://user-images.githubusercontent.com/38964297/44488388-3d271000-a61e-11e8-884f-4b996fcb5b06.png)

**Comment by Danlouis9701** [comment]
Corrección del Tamano del Pattern 2x
Mismo diseno de font size a el blog que se me escapo
Servicios faltaban dos, ya se agregaron.

**Comment by Danlouis9701** [comment]
:white_check_mark: Espacios de trabajo Corregido
:white_check_mark: Muzquiz Corregido
:white_check_mark: Puebla Corregido
:white_check_mark: Moliere Corregido
:white_check_mark: Seneca Corregido
:white_check_mark: Comedores Corregido
:white_check_mark: Cowork Corregido
:white_check_mark: Hamburgo Copy of Muzquiz created
:white_check_mark: Lomas Copy of Muzquiz Created
:white_check_mark: Press Corregido
:white_check_mark: About Corregido
:white_check_mark: Colaboradores Corregido
:white_check_mark: Estudio Corregido
:white_check_mark: Membresias Corregido
:white_check_mark: Bolsa de Trabajo Corregido

**Comment by UrickMacario** [comment]
Hola Dan, ya tiene una linea definida el sitio web, estamos muy contentos que el resultado de esta mancuerna de trabajo. Te comparto un par de detalles que vemos. Si tienes cualquier duda quedo al pendiente.

· Espacios de trabajo Corregido: Se ve un bloque de texto debajo del card de Muzquiz.
<img width="712" alt="screen shot 2018-08-28 at 13 46 23" src="https://user-images.githubusercontent.com/26375886/44743681-c7f98600-aac8-11e8-852c-dee942e9ae2a.png">

· Sucursales (muzquiz, puebla, moliere, seneca). esta imagen podrá luego cambiarse a un video? la intención es de que podamos estar cambiando de imagen a video. 
<img width="1110" alt="screen shot 2018-08-28 at 14 03 33" src="https://user-images.githubusercontent.com/26375886/44744682-4c4d0880-aacb-11e8-9466-14ef404029d2.png">

· De esta galería podemos cambiar los dots por los cuadros que estamos manejando.
<img width="645" alt="screen shot 2018-08-28 at 14 06 24" src="https://user-images.githubusercontent.com/26375886/44744816-a057ed00-aacb-11e8-98ab-fcf7e3c348ed.png">

· Sección comedores: La foto debe ocupar el recuadro que te marco en color amarillo.
<img width="1278" alt="screen shot 2018-08-28 at 14 07 41" src="https://user-images.githubusercontent.com/26375886/44744951-f2990e00-aacb-11e8-8e5e-c8e29660c848.png">

**Comment by Danlouis9701** [comment]
Espacios de trabajo Corregido: Se ve un bloque de texto debajo del card de Muzquiz.
**Perdon se me fue el texto lo quito en breve**

esta imagen podrá luego cambiarse a un video? 
**Si puedo colocar el video, solo habría que ver que tenga el tamaño que ya esta definido pero se puede poner videos desde youtube**

 De esta galería podemos cambiar los dots por los cuadros que estamos manejando.?
**podría pero los dots no son código de esa galería, es una imagen, te la comparto y si me ayudas a crear la imagen la cambio, debe quedar igual para que solo reemplace la imagen y no moverle al código y nos tome mas tiempo**
![bullets](https://user-images.githubusercontent.com/38964297/44746931-71447a00-aad1-11e8-8996-14e20a737cb7.png)

Sección comedores: La foto debe ocupar el recuadro que te marco en color amarillo.
**Esto va a estar super complicado, porque para empezar el texto cambia todo el tiempo de tamaño y la imagen se mueve hacia arriba y abajo, estética mente queda mejor enmarcada, le puedo quitar el margen pero cuando el texto sea mas alto que la imagen, debajo de la imagen quedaría un espacio transparente volando, por experiencia, esta es la mejor solución a este tipo de diseño, si quieres lo probamos como quieres pero va a tomar tiempo y sino queda, despúes hay que volver a corregirlo para regresarlo. Tu dime, que hacemos!!

**Comment by UrickMacario** [comment]
**Listo los dots, si los necesitas que los suba al drive, avísame.**
![dots](https://user-images.githubusercontent.com/26375886/44751866-e5394f00-aade-11e8-8feb-09b9585cb6f7.png)

**Sección comedores: La foto debe ocupar el recuadro que te marco en color amarillo.**
Vale no hay problema, que se quede así de momento entonces. Estaba revisando que le hace falta el título a un comedor, adjunto referencia del diseño.
<img width="559" alt="screen shot 2018-08-28 at 16 26 17" src="https://user-images.githubusercontent.com/26375886/44751948-2cbfdb00-aadf-11e8-9f0d-b848a435a3cd.png">
