### ISSUE TITLE
Version Pruebas V0.1

### ISSUE THREAD

**Issue by Danlouis9701** [macario-publico/publico#2]
@UrickMacario  La pagina esta en linea para detectar issues y corregir en la programación antes de lanzar el sitio en el dominio del cliente.

El link de la página es [http://publico.studio-8.co](http://publico.studio-8.co)

Los formularios están  bajo un mail de pruebas, para poder observar su funcionamiento.
El link del buzon para poder entrar y ver que llegan los mails es:
 
[http://study8center.com/webmail](http://study8center.com/webmail)
Username: prueba@studio-8.co
Password: Pueb@s1540

**Comment by UrickMacario** [comment]
Hola @Danlouis9701 , te comparto mis comentarios del sitio, si tienes alguna duda por fa no dudes en comentarla.

Te estaré pasando mañana las fotografías finales para el sitio. 

· preloader inicial - En el drive el cargador final para cambiar por el actual, cambiar afondo blanco
· cambiar texto - pendiente por pasar el texto final
· iconos de servicios - En el drive están los iconos finales (con su nombre final y se agregaron un par) y actualizarlo en todas las secciones donde salgan.
· home / sucursales  - el clic que abarque todo el card.
· home / instagram - agregar clic/link (dirección al instagram) a las fotos.
· home / redes sociales (btn) - linkear correctamente linkedin
· home / footer - no es btn  oficinas y coworking 
· comedor / btn-menu -  agregar pdfs menus (agregados en el drive)
· comedor / btn-domicilio. agregar links : 
  - comedor: https://www.rappi.com.mx/restaurantes/pblico-comedor
  -  itacate: https://www.rappi.com.mx/restaurantes/pblico-itacate
· evento / contacto / horario - podemos poner que se muestre el horario tipo cascada?
· evento / contacto / para cuantas personas: de 5 - 10 personas, 11 - 20, 21 - 50.
· evento / contacto / campos obligatorios menos mensaje
· evento / contacto /  quitar check de aviso de privacidad
· muzquiz / membresías - btn link roto en los cards
· muzquiz / estudio de foto / btn link incorrecto 
· muzquiz / secciones estudiofoto y comedor - centrarlo (esta inclinado a la izq)
· muzquiz / comedor / agregar pdf y btn para rappi
· moliere / comedor / centrarlo (esta inclinado a la izq)
· moliere / comedor / agregar pdf y btn para rappi
· seneca / no lleva apartado de comedor
· puebla / comedor / centrarlo (esta inclinado a la izq)
· hamburgo / secciones:  primer slide / texto / mapa / footer
· lomas / secciones:  primer slide / texto / mapa / footer
· estudio de foto / formulario / quitar aviso de privacidad
· press / linkear a la url de la nota
· membresía / btn link roto de las cards
· menu hamburgs / contacto - link roto
· contacto /  agregar en sucursales de interés: lomas - próximamente otoño’19
· contacto /  agregar en sucursales de interés: hamburgo - próximamente otoño’19
· contacto / para cuantas personas: 1, 2 -5, 5 - 10, 11 - 20, más de 20
· contacto / de donde nos visitas: press, web search, redes y referido
· contacto / campos obligatorios menos mensaje
· contacto /  quitar check de aviso de privacidad
· responsive - galería más grande, se ve muy chica:
<img width="400" alt="screen shot 2018-09-02 at 22 42 21" src="https://user-images.githubusercontent.com/26375886/44966564-8e2de280-af01-11e8-94b6-3f8a2db0d822.png">

Cualquier duda o comentario estoy al pendiente, saludos.
U.

**Comment by UrickMacario** [comment]
Los iconos:
· debe teber la diagonal / no el guión bajo _ 
· Estudio fotográfico tiene demás el "horario 24/7"
· El que se llama NOCOLOCAR no debe de estar 

<img width="597" alt="screen shot 2018-09-06 at 12 29 44" src="https://user-images.githubusercontent.com/26375886/45174556-c9b20080-b1d0-11e8-9955-2fc23a12e1db.png">
<img width="278" alt="screen shot 2018-09-06 at 12 29 36" src="https://user-images.githubusercontent.com/26375886/45174558-c9b20080-b1d0-11e8-85df-a02e771d1e2e.png">
<img width="216" alt="screen shot 2018-09-06 at 12 29 32" src="https://user-images.githubusercontent.com/26375886/45174559-ca4a9700-b1d0-11e8-839d-cb7d40d7e4c2.png">
<img width="155" alt="screen shot 2018-09-06 at 12 29 27" src="https://user-images.githubusercontent.com/26375886/45174560-ca4a9700-b1d0-11e8-8a1a-767d7e6d7080.png">
<img width="221" alt="screen shot 2018-09-06 at 12 29 20" src="https://user-images.githubusercontent.com/26375886/45174632-f9610880-b1d0-11e8-9194-074e9e829ffb.png">


[ ] evento / contacto / para cuantas personas - agregar otro : 50 - 150 personas
[ ] evento / contacto / es para todo el publico - opciones: para la comunidad de PÚBLICO , abierto al publico en general, habra una lista de invitados
[ ] evento / contacto / tipo de evento - opciones: evento privado, evento empresarial, evento cultural, evento para tu marca, evento para la comunidad
[ ] menú , URL y card de sección - es MOLIERE no molier.
[ ] Agregar red social youtube/ en drive dentro de la carpeta iconos esta el SVG / LINK: https://www.youtube.com/channel/UCjE2rqVvUFTovcz7DQelftw/videos
[ ] press / linkear a la url de la nota - Esta sección va estar en constante actualización, por lo tanto. Creo que lo más conveniente es que la vayamos rellenando nosotros:
  - Podrías decirme en que linea del code esta para colocar la URL.
  - como agrego la foto en la card
  - La card completa debe de tener el click
[ ] hamburgo / las secciones que deben tener: primer slide / texto / mapa / footer
  - google maps: https://goo.gl/maps/55QbaDa2r122
[ ] lomas /  las secciones que deben tener: primer slide / texto / mapa / footer
  - Pendiente por compartir
[ ] estudio de foto / formulario - campos obligatorios menos mensaje
[ ] comedor / publico comedor /Agregar solo en /comedor un tercer botón de "Factura electrónica" que lleve a www.publicocomedor.com/factura
[ ] comedor / proximamente / duplicar esta sección abajo y en lugar que diga "proximamente" y el cuerpo de texto: 
  - btn con mail a: eventos@publicocomedor.com / Nombre de btn: mándanos un mail
  - btn para descargar pdf: / ya en drive en carpeta de menus / nombre btn: Ver kit de ventas
[ ] home / Agregar  badge debajo de las redes del primer slide / ya en el drive

<img width="322" alt="screen shot 2018-09-06 at 20 57 06" src="https://user-images.githubusercontent.com/26375886/45194161-77e09900-b217-11e8-9faf-db6900d5c2be.png">


Pendientes:
[ ]  home / instagram - agregar clic/link (dirección al instagram) a las fotos.
[ ]  cambiar texto - pendiente por pasar el texto final
[ ]  muzquiz / membresías - btn link roto en los cards
[ ]  muzquiz / secciones estudiofoto y comedor - centrarlo (esta inclinado a la izq)
[ ]  muzquiz / comedor / agregar pdf y btn para rappi
[ ]  moliere / comedor / centrarlo (esta inclinado a la izq)
[ ]  moliere / comedor / agregar pdf y btn para rappi
[ ]  seneca / no lleva apartado de comedor
[ ]  puebla / comedor / centrarlo (esta inclinado a la izq)
[ ]  membresía / btn link roto de las cards
[ ]  menu hamburgs / contacto - link roto
[ ]  contacto / agregar en sucursales de interés: lomas - próximamente otoño’19
[ ]  contacto / agregar en sucursales de interés: hamburgo - próximamente otoño’19
[ ]  contacto / para cuantas personas: 1, 2 -5, 5 - 10, 11 - 15, más de 15
[ ]  contacto / de donde nos visitas: press, web search, redes y referido
[ ]  contacto / campos obligatorios menos mensaje
[ ]  responsive - galería más grande, se ve muy chica:

![](https://user-images.githubusercontent.com/26375886/44966564-8e2de280-af01-11e8-94b6-3f8a2db0d822.png)


Cualquier duda o comentario avísame.

**Comment by UrickMacario** [comment]
[ ] agregar favicon - ya en drive
[ ] actualización de logos / aliados - se agregaron un par de logos, tmb tendrán un orden especial los primeros 6 que se muestran al inicio. Te lo paso Viernes 7 sep.

**Comment by UrickMacario** [comment]
[ ] Ubicación de google maps Lomas: https://goo.gl/maps/HRjEGPqkeKM2

**Comment by UrickMacario** [comment]
La sección de Lomas123 ahora se va a llamar Prado Norte 225, para cambiarlo en las secciones así como el menú.
