### ISSUE TITLE
LAST FINAL LAST CAMBIOS

### ISSUE THREAD

**Issue by UrickMacario** [macario-publico/publico#4]
· Reemplazar icono de testimonial - archivo de moda / https://drive.google.com/file/d/18QTJQS_Fz6r9RRcgIjoqbju3VF1s9NXa/view?usp=sharing

· En el texto de la sección de contacto (adjunto screen) que diga : ... **para tu empresa:**

![screen shot 2018-10-09 at 10 49 07](https://user-images.githubusercontent.com/26375886/46747477-0f9e3080-cc77-11e8-9bb6-5f1102e6fcf2.png)

· Sección Puebla - apartado próximamente comedor tiene el texto PRÓXIMAMENTE // (adjunto screen), hay que quitárselo. 

![screen shot 2018-10-09 at 10 54 42](https://user-images.githubusercontent.com/26375886/46747761-bb478080-cc77-11e8-89a4-f64e64242a8e.png)

· Sección membresía - en la foto de **escritorios de coworking**, sustituirla por la de escritorios de coworking seneca. // ya que se repite en slide principal y card.

· Sección de colaboradores, agregar btn (como el de Pablo salas) para:
- Allan legaspi su btn redirige a https://industrialbypubli.co/
- Alfonso su btn redirige a https://www.facebook.com/studio.inh
- Cecilia su btn redigie a - https://coolhuntermx.com/cecilia-leon-de-la-barra/

El apartado de bolsa de trabajo de momento hay que ocultar esa sección

- Para las fotos en responsive te las entrego hoy por la tarde/noche. (en una nueva carpeta)

**Comment by UrickMacario** [comment]
**Listo la nota del blog faltante (iría en la primera posición)**
foto: https://drive.google.com/open?id=1owh-TRdjyEm_mAgd-kPNAS5iY4brKozr
- título: “PÚBLICO gana el Members’ Choice Award 2018 de la Ciudad de México otorgado por Coworker”
- texto: PÚBLICO ha sido nombrado como el ganador de los Members’ Choice Award 2018 Mexico City, evento organizado por Coworker. Los acreedores de este reconocimiento se determinaron con base en los cientos de comentarios, votos y opiniones recopilados en un sólo año por miembros de los espacios de coworking en todo el mundo. 
link: https://www.publi.co/blog/publico-gana-el-members-choice-award-2018-de-la-ciudad-de-mexico-otorgado-por-coworker/

**Fotos de primer slide para versión mobile listas, no todas cambian ya que hay un par que se adaptan/ven bien sin problema, el nombre del archivo es la sección donde iría.** 
Fotos: https://drive.google.com/open?id=1psdKkdclMKR6zsbl3sBNgPJ-EgY6Jhu4

**Sección de press: 
· te comparto el listado final de los links con sus títulos, ya van en orden.**
https://docs.google.com/document/d/1NuQ8MhDcSgtqb7Sv1HiPO4dLEuBiD0uWcak9QNAL0jY/edit?usp=sharing

·fotografías - el nombre de la foto es el nombre de la nota
https://drive.google.com/open?id=1zKB2Bl2nxYdf_wuCgblH3Bb8nNfD5ySx

**Comment by Danlouis9701** [comment]
Sección de press:
· te comparto el listado final de los links con sus títulos, ya van en orden.
### Habíamos platicado que esto entraría en Mantenimiento

**Comment by UrickMacario** [comment]
Hola Dan.

A esto me refería el video esta grande en mobile, la primera imagen es como se ve a primera instancia y la segunda es cuando se muestra el desfase.

<img width="402" alt="1" src="https://user-images.githubusercontent.com/26375886/46826790-87925680-cd5c-11e8-8d0f-0ead183eadf4.png">


<img width="399" alt="2" src="https://user-images.githubusercontent.com/26375886/46826801-8bbe7400-cd5c-11e8-9f4c-0c80584fe4bf.png">



Los scripts para SEO: 
https://drive.google.com/open?id=1lmFU_dxvZoWwXnyNOTvJehFoxGvLyrlF

**Comment by UrickMacario** [comment]
pass:  uKYPS@4k+pJ~
usuario: publico
http://publi.co/cpanel

**Comment by UrickMacario** [comment]
fotos instagram links ( orden / link) 
1 / https://www.instagram.com/p/Bg2c_4WlExG/?taken-by=publi.co
2 / https://www.instagram.com/p/BkLgNpVlw8j/?taken-by=publi.co
3 / https://www.instagram.com/p/BhhgQEbF83A/?taken-by=publi.co
4 / https://www.instagram.com/p/BfGmNRgF4CK/?taken-by=publi.co
5 / https://www.instagram.com/p/BiowIPmFoE8/?taken-by=publi.co
6 / https://www.instagram.com/p/BnEXncLF5bb/?taken-by=publi.co
7 / https://www.instagram.com/p/BjeEj4sF2HL/?taken-by=publi.co
8 / https://www.instagram.com/p/BktrOa3leFh/?taken-by=publi.co

fotos para usar: https://drive.google.com/open?id=18blrLmk9AJvzdVztmqhi1Sa8jFqDCEvs

**Comment by Danlouis9701** [comment]
1. Pendiente el password del mail y la cuenta a la que enviaran los correos 
2. Pendiente saber en donde se debe poner el script de las campañas

**Comment by Danlouis9701** [comment]
## Solo se debe poner esto en todas las hojas ?

<script type="application/ld+json">
	    {
	      "@context": "http://schema.org",
	      "@type": "Organization",
	      "url": “https://publi.co",
	      "name": “Público Coworking CDMX",
	      "contactPoint": {
	        "@type": "ContactPoint",
	        "email": “info@publi.co",
	 	"telephone": “+525514542531",
	        "contactType": "Sales"
	      }
	    }
	</script>
	<script type="application/ld+json">
	  {
	    "@context": "http://schema.org",
	    "@type": "LocalBusiness",
	    "address": {
	    "@type": "PostalAddress",
	    "addressLocality": "Ciudad de Mexico",
	    "addressRegion": "CDMX",
	    "postalCode":"11850",
	    "streetAddress": "Gobernador Melchor Muzquiz 15"
	    },
	    "description": "Público Coworking CDMX",
	    "name": "Público Muzquiz",
	    "telephone": "+525514542531",
	    "openingHours": "Mo-Sun 00:00-23:59",
	    "geo": {
	    "@type": "GeoCoordinates",
	    "latitude": "19.4120733",
	    "longitude": "-99.1898365"
	    },      
	    "sameAs" : [ "https://www.facebook.com/PUBLICOtrabajo",
	    "https://twitter.com/publicotrabajo",
	    "https://www.instagram.com/publi.co/"],
	    "image": "https://publi.co/wp/wp-content/uploads/2018/04/Publico_Coworking_Muzquiz15_espacios_en_renta_CDMX_San_Miguel_Chapultepec_MOBILE.jpg",
	    "priceRange": "4000-70000"
	  }
	</script>

**Comment by UrickMacario** [comment]
**INDEX**

Ciudad de México FALTA MAYÚSCULA Y ACENTO
<img width="890" alt="screen shot 2018-10-12 at 14 24 26" src="https://user-images.githubusercontent.com/26375886/46889855-93e4e500-ce2a-11e8-8540-1a2c17e668f1.png">

Quitar el punto demás del final de la oración.
<img width="816" alt="screen shot 2018-10-12 at 14 25 13" src="https://user-images.githubusercontent.com/26375886/46889921-d3abcc80-ce2a-11e8-9ea2-5a711a2b809e.png">

**SECCIÓN EVENTOS**
Nos falto poner un evento y esta mal una descripción. Texto correcto:

Eventos privados: Privados: veladas familiares, celebraciones especiales, reuniones con clientes potenciales… Tu espacio para celebrar.
Eventos empresariales: Capacitaciones, eventos de integración, congresos y conferencias.
Eventos culturales: Lanzamientos de obras, Exposiciones de arte, showrooms.
Eventos para tu marca: Pop ups, lanzamientos de productos, eventos de crowdfunding.
Eventos para la comunidad: Clases de meditación y yoga, talleres y workshops para emprendedores, diseñadores, fotógrafos. PÚBLICO es tu aliado en difundir tus habilidades.

<img width="1049" alt="screen shot 2018-10-12 at 14 36 56" src="https://user-images.githubusercontent.com/26375886/46890465-97796b80-ce2c-11e8-91da-a0d253b873f7.png">

cambiar texto antes del formulario:
Platícanos sobre tu evento ¿Qué tienes en mente? ¡Déjalo en nuestras manos!
Tu evento en PÚBLICO
<img width="1139" alt="screen shot 2018-10-12 at 14 39 55" src="https://user-images.githubusercontent.com/26375886/46890519-b841c100-ce2c-11e8-99fb-11cddb8b4d0d.png">

**MUZQUIZ**

· El btn de conócenos le hace falta acento.
<img width="976" alt="screen shot 2018-10-12 at 14 41 32" src="https://user-images.githubusercontent.com/26375886/46890612-f50db800-ce2c-11e8-8650-ad21f882847e.png">

**JUAREZ**
· Debe decir: nuestro en vez de nuestra
<img width="1014" alt="screen shot 2018-10-12 at 14 42 46" src="https://user-images.githubusercontent.com/26375886/46890657-1a022b00-ce2d-11e8-8ee7-7a450ef7dae2.png">

**LOMAS**
· mismo error de la palabra nuestro
<img width="988" alt="screen shot 2018-10-12 at 14 43 29" src="https://user-images.githubusercontent.com/26375886/46890686-343c0900-ce2d-11e8-9461-3bb45dce0e2f.png">

**JUAREZ Y LOMAS**
· La palabra SÉ en el btn va acentuada.
<img width="1179" alt="screen shot 2018-10-12 at 14 44 13" src="https://user-images.githubusercontent.com/26375886/46890740-5897e580-ce2d-11e8-8e04-e97573c2a70a.png">


**PUEBLA**
· cambiar el título a "Ubicado cerca de Reforma..."

<img width="878" alt="screen shot 2018-10-12 at 14 45 41" src="https://user-images.githubusercontent.com/26375886/46890852-b2001480-ce2d-11e8-82e6-e8ca9089ea19.png">


**MOLIERE Y SENECA**
· cambiar el título a " Público se encuentra en 2 ubicaciones en Polanco"
<img width="905" alt="screen shot 2018-10-12 at 14 46 55" src="https://user-images.githubusercontent.com/26375886/46890877-c47a4e00-ce2d-11e8-83f8-d1fdeae4dbf4.png">

**ESPACIOS DE TRABAJO**
· Cambiar texto por: "Hemos creado una experiencia para el usuario basada en sus necesidades. Conoce nuestros beneficios:"

<img width="987" alt="screen shot 2018-10-12 at 14 49 31" src="https://user-images.githubusercontent.com/26375886/46890957-0a371680-ce2e-11e8-9b4a-15f072f42de8.png">

**ABOUT US**
· Falta acento PÚBLICO en el título del slider.
